const Type = {
  Grass: 1,
  Fire: 2,
  Water: 3,
  Electric: 4,
  Ground: 5,
  Bug: 6,
  Rock: 7,
  Poison: 8,
};

const PokemonList = [
  {
    no: 1,
    name: "Bulbasaur",
    description: "Awesome pokemon",
    type: [Type.Grass, Type.Poison],
    hp: 3,
    atk: 3,
    def: 3,
    satk: 4,
    sdef: 4,
    spd: 3,
  },
  {
    no: 4,
    name: "Charmander",
    description: "Awesome pokemon",
    type: [Type.Fire],
    hp: 3,
    atk: 4,
    def: 3,
    satk: 4,
    sdef: 3,
    spd: 4,
  },
  {
    no: 7,
    name: "Squirtle",
    description: "Awesome pokemon",
    type: [Type.Water],
    hp: 4,
    atk: 3,
    def: 4,
    satk: 3,
    sdef: 4,
    spd: 3,
  },
  {
    no: 25,
    name: "Pikachu",
    description: "Awesome pokemon",
    type: [Type.Electric],
    hp: 3,
    atk: 4,
    def: 3,
    satk: 3,
    sdef: 3,
    spd: 6,
  },
  {
    no: 50,
    name: "Diglett",
    description: "Awesome pokemon",
    type: [Type.Ground],
    hp: 2,
    atk: 4,
    def: 2,
    satk: 3,
    sdef: 2,
    spd: 4,
  },
  {
    no: 10,
    name: "Caterpie",
    description: "Awesome pokemon",
    type: [Type.Bug],
    hp: 2,
    atk: 3,
    def: 2,
    satk: 2,
    sdef: 2,
    spd: 3,
  },
  {
    no: 74,
    name: "Geodude",
    description: "Awesome pokemon",
    type: [Type.Rock, Type.Ground],
    hp: 3,
    atk: 4,
    def: 4,
    satk: 2,
    sdef: 3,
    spd: 2,
  },
];

export { PokemonList, Type };
